### PR TITLE
add test for MathJax/MathJax#375 Process \{ \} \ in \text{}

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by dpvc** [comment]
I think this test could be improved.  The issue is purely about input processing, but you are testing the output produced, which adds an extra level of complication that you don't need, as this relies on the output being of a particular form.  This fails for SVG output, for example, but the test should not depend on the output processor, since it is just about input.

I'd recommend either doing a tree refttest like most of the other ones in the LaTeXToMathML directory, or testing the internal format directly.  For example, something like

``` javascript
function getTestCases() {
  var math = MathJax.Hub.getAllJax()[0].root;
  return [
    newScriptReftestResult("Escaped braces and backslash work ",
      math.data[0].data[0].data.join("") === "{}\\")
  ];
}
```

with

```
\( \text{\{\}\\} \)
```

would be more direct and not involve the output jax at all.

**Comment by dpvc** [comment]
Alternatively, you could use

``` javascript
function getTestCases() {
  var math = MathJax.Hub.getAllJax()[0].root;
  return [
    newScriptReftestResult("Escaped braces and backslash work ",
      math.toString() === "math([mtext({}\\)])")
  ];
}
```

which tests if the entire math element has the proper structure and content.  (The `toString()` method doesn't show any attributes of the math elements, only their nesting and contents, and was originally intended for debugging, but is useful for this type of quick test as well.)

**Comment by pkra** [comment]
Meh, I thought I had tested SVG. Will change it (don't quite understand why the reftree is in a separate document but will follow the style instead of your much nicer second suggestion :-) ).

**Comment by dpvc** [comment]
I agree that it would be more efficient to have the reference in the same file.  Not sure why that was done, but it may have come from Mozilla's test suite originally, where they would need to test entire HTML DOM trees, and so they would have to be in separate files.  We are only testing subtrees, so could have them in the same file.

That could be part of a redesign when we overhaul the testing framework.

**Comment by pkra** [comment]
I'm not sure how to locally test a reftest. But here's an attempt.

**Comment by dpvc** [comment]
You can't really do it well by hand.  You would have to copy the output from the two retest windows into files and do a diff on them.  I just run the testsuite having selected only the one file in order to do the testing.  I run it twice, once with the develop branch and once with the master branch to see that the master fails and the develop passes.

Because script tests don't require actually running the testsuite, that is another reason I prefer them over thither test types.  Another problem with tree reftests is that if the MathML generated from the TeX input jax changes, you have to change the reference page as well.  I've run into that a lot of times as we fix TeX issues.  Of course, my suggestions above might also require adjustment in those cases, as well.

**Comment by dpvc** [comment]
I've tested your files, and they work properly.  I will merge.

**Pull request merged**
